### ISSUE TITLE
CC1101 ino file won't compile

### ISSUE THREAD

**Issue by sensorhost** [andi38/TPMS#9]
Hi, i would like to try this code however it won't compile.

I have an ATMega1284 on a custom PCB running at 3.3V.
I am using Arduino Mightycore in Arduino IDE version 2.3.7

The error I am getting is
```error: no matching function for call to 'CC1101::setGdo0Action(void (&)())'
   radio.setGdo0Action(setFlag);

CC1101.h:666:10: note: candidate: void CC1101::setGdo0Action(void (*)(), uint32_t)
     void setGdo0Action(void (*func)(void), uint32_t dir);

CC1101.h:666:10: note:   candidate expects 2 arguments, 1 provided
```

Any guidance is appreciated.

**Comment by sensorhost** [comment]
It seems I need to specify (in addition to the example provided here) the interrupt type.
I am guessing this will be either CHANGE, RISING, or FALLING. If this is true, which one should I use?

**Comment by andi38** [comment]
Hi, it seems to me that the underlying library RadioLib (https://github.com/jgromes/RadioLib) might have changed.
1. Try to compile with version v5.3.0.
2. As right now I have no equipment available to adapt and in particular test with current RadioLib version, I would like to point you to:
- https://github.com/jgromes/RadioLib?tab=readme-ov-file#supported-arduino-platforms
- https://github.com/jgromes/RadioLib/blob/master/examples/CC1101/CC1101_Receive_Interrupt/CC1101_Receive_Interrupt.ino
The example file CC1101_Receive_Interrupt.ino is the base, where you might add the TPMS decoding part from lines 172ff of file CC1101_TPMS_433.ino.
It seems that the function radio.setGdo0Action(setFlag) has changed to radio.setPacketReceivedAction(setFlag).
Furthermore - although I do not know if still necessary - the godmode is now enabled in file BuildOpt.h and still has the warning that you might brick the module.
